# Makefile.dep created Thu Feb 28 15:37:49 PST 2019
logstream.o: logstream.h
protocol.o: protocol.h sockets.h
protocol.o: protocol.cpp protocol.h sockets.h
sockets.o: sockets.h
sockets.o: sockets.cpp sockets.h
cix.o: cix.cpp protocol.h sockets.h logstream.h
cixd.o: cixd.cpp protocol.h sockets.h logstream.h
