# $Id: Makefile,v 1.3 2016-05-05 13:30:20-07 - - $

MKFILE      = Makefile
DEPFILE     = ${MKFILE}.dep
NOINCL      = ci clean spotless
NEEDINCL    = ${filter ${NOINCL}, ${MAKECMDGOALS}}
GMAKE       = ${MAKE} --no-print-directory
WARNINGS    = -Wall -Wextra -Wold-style-cast
COMPILECPP  = g++ -g -O0 ${WARNINGS} -std=gnu++14
MAKEDEPCPP  = g++ -MM -std=gnu++14

MODULES     = debug graphics interp rgbcolor shape util main
CPPHEADER   = $(wildcard ${MODULES:=.h})
CPPSOURCE   = $(wildcard ${MODULES:=.cpp})
TCCFILES    = $(wildcard ${MODULES:=.tcc})
GENFILES    = colors.cppgen
SOURCES     = $(wildcard ${foreach MOD, ${MODULES}, \
                 ${MOD}.h ${MOD}.tcc ${MOD}.cpp})
OTHERS      = ${MKFILE} ${DEPFILE} mk-colors.perl
ALLSOURCES  = ${SOURCES} ${OTHERS}
EXECBIN     = gdraw
OBJECTS     = ${CPPSOURCE:.cpp=.o}
LINKLIBS    = -lGL -lGLU -lglut -lm

LISTING     = Listing.ps
CLASS       = cmps109-wm.u16
PROJECT     = asg4

all : ${EXECBIN}
	- checksource ${ALLSOURCES}

echo :
	- echo ${ALLSOURCES}

${EXECBIN} : ${OBJECTS}
	${COMPILECPP} -o $@ ${OBJECTS} ${LINKLIBS}

%.o : %.cpp
	${COMPILECPP} -c $<

colors.cppgen: mk-colors.perl
	mk-colors.perl >colors.cppgen

ci : ${ALLSOURCES}
	- checksource ${ALLSOURCES}
	cid + ${ALLSOURCES}

lis : ${ALLSOURCES}
	mkpspdf ${LISTING} ${ALLSOURCES} ${DEPFILE}

clean :
	- rm ${OBJECTS} ${DEPFILE} core ${GENFILES}

spotless : clean
	- rm ${EXECBIN} ${LISTING} ${LISTING:.ps=.pdf}


submit : ${ALLSOURCES}
	- checksource ${ALLSOURCES}
	submit ${CLASS} ${PROJECT} ${ALLSOURCES}

dep : ${CPPSOURCE} ${CPPHEADER} ${TCCFILES} ${GENFILES}
	@ echo "# ${DEPFILE} created `LC_TIME=C date`" >${DEPFILE}
	${MAKEDEPCPP} ${CPPSOURCE} >>${DEPFILE}

${DEPFILE} :
	@ touch ${DEPFILE}
	${GMAKE} dep

again :
	${GMAKE} spotless dep ci all lis

ifeq (${NEEDINCL}, )
include ${DEPFILE}
endif

